# /etc/rsyslog.d/sentraid.conf

input(
    type="imfile"
    File="/opt/sentraID/logs/sentraid.log"
    Tag="sentraID"
    Facility="local6"
    Severity="info"
    PersistStateInterval="100"
)

if $programname == "sentraID" then {
    action(
        type="omfwd"
        Target="<SYSLOG_HOST>"
        Port="514"
        Protocol="tcp"
        TCP_Framing="octet-counted"
        KeepAlive="on"
        Action.ResumeRetryCount="-1"
    )
    stop
}

